"""empty message

Revision ID: f3604886370f
Revises: 6a93101caac0
Create Date: 2024-11-02 02:28:39.855846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3604886370f'
down_revision = '6a93101caac0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cutscenes')
    op.drop_table('characters')
    op.drop_table('case_cutscene')
    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('answer', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('background_image', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('reward', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('locked', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('video', sa.String(), nullable=True))
        batch_op.alter_column('clues',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.drop_column('answers')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('height',
               existing_type=sa.FLOAT(),
               type_=sa.Integer(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('height',
               existing_type=sa.Integer(),
               type_=sa.FLOAT(),
               existing_nullable=True)

    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('answers', sa.TEXT(), nullable=False))
        batch_op.alter_column('clues',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.drop_column('video')
        batch_op.drop_column('locked')
        batch_op.drop_column('reward')
        batch_op.drop_column('background_image')
        batch_op.drop_column('answer')
        batch_op.drop_column('description')
        batch_op.drop_column('title')

    op.create_table('case_cutscene',
    sa.Column('case_id', sa.INTEGER(), nullable=False),
    sa.Column('cutscene_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['cutscene_id'], ['cutscenes.id'], ),
    sa.PrimaryKeyConstraint('case_id', 'cutscene_id')
    )
    op.create_table('characters',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('image', sa.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('cutscenes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('text', sa.TEXT(), nullable=False),
    sa.Column('image', sa.VARCHAR(length=255), nullable=True),
    sa.Column('character_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
